#pragma once

#define TE_MAX_DIRECTORIES   20
#define TE_VIRTUAL_DIR_POOL  32
#define TE_MAX_FILENAME_SIZE 128

#define TE_MAX_PLAYERS 8
#define TE_MAX_GAMEPADS 8
#define TE_MAX_JOYSTICKS 8
#define TE_UNASSIGNED_INPUT -1